// <auto-generated />
using System;
using FreakyFashion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreakyFashion.Migrations
{
    [DbContext(typeof(FreakyFashionContext))]
    [Migration("20200213203306_AddAdminUser")]
    partial class AddAdminUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FreakyFashion.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("UrlSlug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUri = "/img/campaign.jpg",
                            IsHighlighted = true,
                            Name = "Campaign",
                            UrlSlug = "campaign-19f6dde9-c744-45f3-906c-615d47033574"
                        },
                        new
                        {
                            Id = 2,
                            ImageUri = "/img/news.jpg",
                            IsHighlighted = true,
                            Name = "News",
                            UrlSlug = "news-b4304a8a-3e20-4cd6-a73d-2e9a81a55f94"
                        },
                        new
                        {
                            Id = 3,
                            ImageUri = "/img/spring.jpg",
                            IsHighlighted = true,
                            Name = "Spring",
                            UrlSlug = "spring-5a30dc7b-8903-4537-91ef-90e6c8e08e6e"
                        },
                        new
                        {
                            Id = 4,
                            ImageUri = "/img/shirt_01.jpg",
                            IsHighlighted = false,
                            Name = "Shirts",
                            UrlSlug = "shirts-ff7dcfcc-caff-4c5b-a7d0-e86100485829"
                        },
                        new
                        {
                            Id = 5,
                            ImageUri = "/img/blouse_01.jpg",
                            IsHighlighted = false,
                            Name = "Blouses",
                            UrlSlug = "blouses-fda6d09e-eb6d-459c-9e44-5fd914ca5faf"
                        },
                        new
                        {
                            Id = 6,
                            ImageUri = "/img/jeans_01.jpg",
                            IsHighlighted = false,
                            Name = "Jeans",
                            UrlSlug = "jeans-7f81f8ec-4af9-4c1e-8099-dba5724fc420"
                        },
                        new
                        {
                            Id = 7,
                            ImageUri = "/img/dress_01.jpg",
                            IsHighlighted = false,
                            Name = "Dresses",
                            UrlSlug = "dresses-dff6a830-11a1-4022-90cd-328ffa6f9d0f"
                        });
                });

            modelBuilder.Entity("FreakyFashion.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArticleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleNumber = "12345-6789",
                            Description = "Do you want to be the one to stand out in a crowd? This skirt will fit for any occasion",
                            ImageUri = "/img/product_01.jpg",
                            Name = "Crazy skirt",
                            Price = 499.89999999999998,
                            UrlSlug = "crazy-skirt-d82cd45f-b21b-47e7-a1f3-a089bf9e07b0"
                        },
                        new
                        {
                            Id = 2,
                            ArticleNumber = "98765-4321",
                            Description = "These pants will certainly get you the attention you deserve. Be brave, be free, be wild",
                            ImageUri = "/img/product_02.jpg",
                            Name = "Wild pants",
                            Price = 899.89999999999998,
                            UrlSlug = "wild-pants-efdd6976-df3c-4e46-b019-784ce3258e33"
                        },
                        new
                        {
                            Id = 3,
                            ArticleNumber = "21543-9876",
                            Description = "This jacket will keep you both warm and dazzling. It comes in many vibrant colours. What is your furry?",
                            ImageUri = "/img/product_03.jpg",
                            Name = "Furry coatee",
                            Price = 1299.9000000000001,
                            UrlSlug = "furry-coatee-3abd0c2f-f587-4569-84d6-14de5aba2d57"
                        },
                        new
                        {
                            Id = 4,
                            ArticleNumber = "32145-8769",
                            Description = "You will be the center of all attention, 100% guarantee!Gorgeous will bring out your freaky. Get ready to party!",
                            ImageUri = "/img/blouse_01.jpg",
                            Name = "Gorgeous blouse",
                            Price = 349.94999999999999,
                            UrlSlug = "gorgeous-blouse-9a9eb725-deb6-4037-9aff-08069886fc81"
                        },
                        new
                        {
                            Id = 5,
                            ArticleNumber = "42137-2897",
                            Description = "This is deffinately THE dress.You will see shapes you didn't know you had.",
                            ImageUri = "/img/dress_01.jpg",
                            Name = "Green flower dress",
                            Price = 3599.9000000000001,
                            UrlSlug = "green-flower-dress-7dca5087-b74d-45e2-bf4b-ef5f0fddfdf4"
                        },
                        new
                        {
                            Id = 6,
                            ArticleNumber = "67921-5690",
                            Description = "Too cool for school? Get theese jeans today!",
                            ImageUri = "/img/jeans_01.jpg",
                            Name = "Cool jeans",
                            Price = 699.0,
                            UrlSlug = "cool-jeans-8fb007b2-1d28-46b1-94d6-6ca2cc326292"
                        },
                        new
                        {
                            Id = 7,
                            ArticleNumber = "75641-0876",
                            Description = "You feel bad? No you are just freaky!Show the real you.",
                            ImageUri = "/img/shirt_01.jpg",
                            Name = "Bad girl shirt",
                            Price = 295.0,
                            UrlSlug = "bad-girl-shirt-4567063a-3370-4a89-a9ac-7b0a595f132d"
                        },
                        new
                        {
                            Id = 8,
                            ArticleNumber = "29064-8514",
                            Description = "Own the beach this summer? Of course you wantWhat are you waiting for?",
                            ImageUri = "/img/dress_02.jpg",
                            Name = "Freaky beach dress",
                            Price = 595.0,
                            UrlSlug = "freaky-beach-dress-b8890761-25d3-4340-967e-6d85d6ccd86f"
                        },
                        new
                        {
                            Id = 9,
                            ArticleNumber = "85201-6354",
                            Description = "Casual, comfortable, enjoyable!No need to get stiff in theese pants",
                            ImageUri = "/img/jeans_02.jpg",
                            Name = "Get dirty jeans",
                            Price = 899.0,
                            UrlSlug = "get-dirty-jeans-e0dd4cfa-b8f1-4f81-b473-7122ce195b4b"
                        },
                        new
                        {
                            Id = 10,
                            ArticleNumber = "50945-3165",
                            Description = "Are you a Pepsi fan? Show it to the world!",
                            ImageUri = "/img/shirt_02.jpg",
                            Name = "Pepsi Cola shirt",
                            Price = 99.0,
                            UrlSlug = "pepsi-cola-shirt-f156809a-4e21-48cc-88d3-6881e8b0759d"
                        },
                        new
                        {
                            Id = 11,
                            ArticleNumber = "20975-8647",
                            Description = "Elegant, beautiful, yes just gorgeous - Or as we say: Smokin'",
                            ImageUri = "/img/dress_03.jpg",
                            Name = "Smokin' dress",
                            Price = 1999.99,
                            UrlSlug = "smokin'-dress-6dd291e6-efb2-4546-8a00-65f787a2513c"
                        });
                });

            modelBuilder.Entity("FreakyFashion.Data.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 7
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "9b803634-477f-4460-9f63-807fe350bde7",
                            ConcurrencyStamp = "eed65a50-8ff7-4a83-9ad5-f8c65a56e9cc",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "feec6ea3-97fb-4aca-8001-27a12f226daf",
                            Email = "admin@nomail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@NOMAIL.COM",
                            NormalizedUserName = "ADMIN@NOMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFgvBb6WDddc3d0HmM0SdTZ5w48QSTPSIIPkJ5R9VkTb0ZzW2wfP4KTukJv9p7Zt2Q==",
                            PhoneNumber = "0707-12345",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35b965ba-cd4d-4ed5-a8a7-eaa08057f9d0",
                            TwoFactorEnabled = false,
                            UserName = "admin@nomail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "9b803634-477f-4460-9f63-807fe350bde7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FreakyFashion.Data.Entities.ProductCategory", b =>
                {
                    b.HasOne("FreakyFashion.Data.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreakyFashion.Data.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
