// <auto-generated />
using FreakyFashion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreakyFashion.Migrations
{
    [DbContext(typeof(FreakyFashionContext))]
    [Migration("20200130130338_SeedMoreProducts")]
    partial class SeedMoreProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FreakyFashion.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUri = "/img/campaign.jpg",
                            IsHighlighted = true,
                            Name = "Campaign"
                        },
                        new
                        {
                            Id = 2,
                            ImageUri = "/img/news.jpg",
                            IsHighlighted = true,
                            Name = "News"
                        },
                        new
                        {
                            Id = 3,
                            ImageUri = "/img/spring.jpg",
                            IsHighlighted = true,
                            Name = "Spring"
                        },
                        new
                        {
                            Id = 4,
                            ImageUri = "/img/shirt_01.jpg",
                            IsHighlighted = false,
                            Name = "Shirts"
                        },
                        new
                        {
                            Id = 5,
                            ImageUri = "/img/blouse_01.jpg",
                            IsHighlighted = false,
                            Name = "Blouses"
                        },
                        new
                        {
                            Id = 6,
                            ImageUri = "/img/jeans_01.jpg",
                            IsHighlighted = false,
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 7,
                            ImageUri = "/img/dress_01.jpg",
                            IsHighlighted = false,
                            Name = "Dresses"
                        });
                });

            modelBuilder.Entity("FreakyFashion.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Do you want to be the one to stand out in a crowd? This skirt will fit for any occasion",
                            ImageUri = "/img/product_01.jpg",
                            Name = "Crazy skirt",
                            Price = 499.89999999999998
                        },
                        new
                        {
                            Id = 2,
                            Description = "These pants will certainly get you the attention you deserve. Be brave, be free, be wild",
                            ImageUri = "/img/product_02.jpg",
                            Name = "Wild pants",
                            Price = 899.89999999999998
                        },
                        new
                        {
                            Id = 3,
                            Description = "This jacket will keep you both warm and dazzling. It comes in many vibrant colours. What is your furry?",
                            ImageUri = "/img/product_03.jpg",
                            Name = "Furry coatee",
                            Price = 1299.9000000000001
                        },
                        new
                        {
                            Id = 4,
                            Description = "You will be the center of all attention, 100% guarantee!Gorgeous will bring out your freaky. Get ready to party!",
                            ImageUri = "/img/blouse_01.jpg",
                            Name = "Gorgeous blouse",
                            Price = 349.94999999999999
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is deffinately THE dress.You will see shapes you didn't know you had.",
                            ImageUri = "/img/dress_01.jpg",
                            Name = "Green flower dress",
                            Price = 3599.9000000000001
                        },
                        new
                        {
                            Id = 6,
                            Description = "Too cool for school? Get theese jeans today!",
                            ImageUri = "/img/jeans_01.jpg",
                            Name = "Cool jeans",
                            Price = 699.0
                        },
                        new
                        {
                            Id = 7,
                            Description = "You feel bad? No you are just freaky!Show the real you.",
                            ImageUri = "/img/shirt_01.jpg",
                            Name = "Bad girl shirt",
                            Price = 295.0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Own the beach this summer? Of course you wantWhat are you waiting for?",
                            ImageUri = "/img/dress_02.jpg",
                            Name = "Freaky beach dress",
                            Price = 595.0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Casual, comfortable, enjoyable!No need to get stiff in theese pants",
                            ImageUri = "/img/jeans_02.jpg",
                            Name = "Get dirty jeans",
                            Price = 899.0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Are you a Pepsi fan? Show it to the world!",
                            ImageUri = "/img/shirt_02.jpg",
                            Name = "Pepsi Cola shirt",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Elegant, beautiful, yes just gorgeous - Or as we say: Smokin'",
                            ImageUri = "/img/dress_03.jpg",
                            Name = "Smokin' dress",
                            Price = 1999.99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
